---
docker_tls_basepath: '/etc/docker'
docker_tls_keys:
  ca_cert: ""
  server_cert: ""
  server_key: ""
docker_daemon_tls_options:
  containerd: "/run/containerd/containerd.sock"
  tlsverify: true
  tlscacert: "{{ docker_tls_basepath }}/ca.crt"
  tlscert: "{{ docker_tls_basepath }}/server.crt"
  tlskey: "{{ docker_tls_basepath }}/server.key"
  hosts: ["tcp://0.0.0.0:2376", "fd://"]
